name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      app-path:
        description: 'Select App Path'
        required: true
        default: 'staging'
        type: choice
        options:
          - '/var/www/vhosts/multisender.easy-go.me'
          - '/var/www/vhosts/multisender.easy-go.me_test_deploy'

jobs:
  vars:
    name: Vars Job
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'
    outputs:
      environment: ${{ github.event.inputs.environment }}
      artifact-name: 'back_dist'
      artifact-path: 'dist'
      node-version: '22'
      app-path: ${{ github.event.inputs.app-path }}
    steps:
      - run: echo "Set production environment variables"
