name: Test Deploy Connections
on:
  workflow_dispatch:
  push:
  workflow_call:

jobs:

  vars:
    name: Vars Job
    runs-on: ubuntu-latest
    outputs:
      artifact-name: 'build-output'
      artifact-path: 'dist'
      node-version: '22'
    steps:
      - run: echo "Set production environment variables"

  dummy_build:
    needs: vars
    name: Build( Dummy )
    runs-on: ubuntu-latest
    outputs:
      build-directory: ${{ steps.build-step.outputs.build-directory }}
      artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        id: build-step
        run: |
          mkdir -p dist
          echo "tetetetete" >> dist/test.txt
          echo "build-directory=$(pwd)/dist" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.vars.outputs.artifact-name }}
          path: 'dist'

  echo:
    needs:
      - vars
      - dummy_build
    name: Echo Job
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'

  deploy_prod:
    name: Deploy Job ( Prod )
    needs:
      - vars
      - dummy_build
    uses: ./.github/workflows/_prod_deploy.yml
    with:
      app-path: '/var/www/vhosts/multisender.easy-go.me_test_deploy'
      artifact-name: ${{ needs.vars.outputs.artifact-name }}
      artifact-path: ${{ needs.vars.outputs.artifact-path }}
    secrets: inherit

  deploy_stg:
    name: Deploy Job ( Stg )
    needs:
      - vars
      - dummy_build
    uses: ./.github/workflows/_stg_deploy.yml
    with:
      app-path: '/var/www/vhosts/stg-multisender.easy-go.me_test_deploy'
      artifact-name: ${{ needs.vars.outputs.artifact-name }}
      artifact-path: ${{ needs.vars.outputs.artifact-path }}
    secrets: inherit